Fix pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -16,27 +16,25 @@ STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep -E 'clien
 
 echo -e "Linting these files in the client directory:\n"
 
-if [[ "$STAGED_FILES" = "" ]]; then
-  exit 0
-else
+if [[ "$STAGED_FILES" != "" ]]; then
   for file in ${STAGED_FILES[@]}; do
     echo $file
   done
-fi
 
-cd client
-echo -e "\nNew directory: $(pwd)\n"
-$ESLINT --fix "${STAGED_FILES[@]}"
-ESLINT_EXIT="$?"
+  cd client
+  echo -e "\nNew directory: $(pwd)\n"
+  $ESLINT --fix "${STAGED_FILES[@]}"
+  ESLINT_EXIT="$?"
 
-# Re-add files since they may have been changed
-git add "${STAGED_FILES[@]}"
+  # Re-add files since they may have been changed
+  git add "${STAGED_FILES[@]}"
 
-if [[ "${ESLINT_EXIT}" == 0 ]]; then
-  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
-else
-  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
-  exit 1
+  if [[ "${ESLINT_EXIT}" == 0 ]]; then
+    printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
+  else
+    printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
+    exit 1
+  fi
 fi
 
 # SERVER
@@ -45,27 +43,25 @@ STAGED_FILES=($(git diff --cached --name-only --diff-filter=ACM | grep -E 'serve
 
 echo -e "Linting these files in the server directory:\n"
 
-if [[ "$STAGED_FILES" = "" ]]; then
-  exit 0
-else
+if [[ "$STAGED_FILES" != "" ]]; then
   for file in ${STAGED_FILES[@]}; do
     echo $file
   done
-fi
 
-cd server
-echo -e "\nNew directory: $(pwd)\n"
-$ESLINT --fix "${STAGED_FILES[@]}"
-ESLINT_EXIT="$?"
+  cd server
+  echo -e "\nNew directory: $(pwd)\n"
+  $ESLINT --fix "${STAGED_FILES[@]}"
+  ESLINT_EXIT="$?"
 
-# Re-add files since they may have been changed
-git add "${STAGED_FILES[@]}"
+  # Re-add files since they may have been changed
+  git add "${STAGED_FILES[@]}"
 
-if [[ "${ESLINT_EXIT}" == 0 ]]; then
-  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
-else
-  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
-  exit 1
+  if [[ "${ESLINT_EXIT}" == 0 ]]; then
+    printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
+  else
+    printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
+    exit 1
+  fi
 fi
 
 exit $?
